# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
#    - DISTRIB="ubuntu" PYTHON_VERSION="2.6" COVERAGE="false"
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_script:
  - git config --global user.email "roskakori@users.sourceforge.net"
  - git config --global user.name "Thomas Aglassinger"
script:
  - python setup.py sdist --formats=zip
  - python setup.py bdist_wheel --universal
  - python setup.py test
  - if [[ "$PYTHON_VERSION" == "3.5" ]]; then python setup.py doctest || echo "failed"; fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
